/**
 * Schema type definitions.
 *
 * This file is NOT auto-generated — manual edits are preserved across schema syncs.
 *
 * WHY THIS FILE EXISTS:
 * The `SchemaEntry` type was originally added to `src/data/schemas/index.ts`, but that
 * file is fully regenerated by `scripts/sync-schemas.js` on every schema sync. When the
 * auto-sync script ran (commit 430eb38a), it removed the manually-added `SchemaEntry`
 * type, breaking the build.
 *
 * To prevent this from happening again, we've moved `SchemaEntry` to this standalone
 * types file that is never touched by auto-generation. All schema-related types that
 * need to survive schema syncs should live here.
 */

/** Metadata-wrapped schema entry. All registered schemas must provide description and group. */
export type SchemaEntry = {
  schema: Record<string, any>;
  description: string;
  group: string;
};
